### ISSUE TITLE
Retrieving imputed Raw Counts

### ISSUE THREAD

**Issue by gufranca** [ikwak2/DrImpute#1]
Hi!
I am very interested in using DrImpute in my scRNA-seq data. I already tried the vignette example and I was very happy to see how easy it is to use the package. I was just wondering: It would be possible to recover the imputed data as Raw counts, instead of normalized counts? How should I proceed to get the imputed raw counts?

I appreciate any help on this!
Gustavo

**Comment by gufranca** [comment]
Oh, I guess it's just providing the Raw Counts to DrImpute function instead of the normalized values, right?
By doing so, does it harm the imputing procedure?

**Comment by ikwak2** [comment]
Hi gufranca, 

In the pipeline of our analysis include normalization by cell. We assumed that researcher do any normalization of this type (one example is https://academic.oup.com/bioinformatics/article/33/8/1179/2907823). The most easy one is normalizing it by total read count. 
We thought that users would use our implication method after standardization by each cell. 
If the data is not necessarily returned as an integer, it is recommended to use our method after proper normalization by cell.
Otherwise, you might need to round up or down to make it as integer return. 

Thank you ! :)

**Comment by gufranca** [comment]
Thanks for the reply! I figured that out!
Best
Gustavo
